Ext.define('desloc.model.InsAbrPreM',{
    extend:'Ext.data.Model',
    fields:[

       {name:'mesref'},
       {name:'seqpla'},
       {name:'destrp'},
       {name:'dessts'},
       {name:'qtdcli'},
       {name:'qtdkm'},
       {name:'vlrpre'},
       {name:'nomfun'},
       {name:'nomloc'},
       {name:'numseq'},
       {name:'tiptrp'},
       {name:'vlrtrp'},
       {name:'valpass'},
       {name:'stspre'},
       {name:'numcad'},
       {name:'juspre'},
       {name:'titred'},
       {name:'dtfim'}
    ]
});